const productCategories = [
  "Electronics",
  "Beauty products",
  "Health care",
  "Home appliances",
  "Clothing and fashion accessories",
  "Automotive parts and accessories",
  "Sports and fitness equipment",
  "Toys and games",
  "Furniture and home decor",
  "Books and literature",
  "Pet supplies",
  "Food and beverages",
  "Office supplies",
  "Outdoor and gardening equipment",
  "Travel and luggage accessories",
  "Baby and maternity products",
  "Jewelry and accessories",
  "Musical instruments and equipment",
  "Art and craft supplies",
  "Home improvement and tools",
];

const buyerInterests = [
  "Apple devices",
  "Beauty products",
  "Wireless earbuds",
  "Gardening equipment",
  "Fitness and workout gear",
  "Home decor and interior design",
  "Travel and adventure gear",
  "Organic and sustainable products",
  "Gaming consoles and accessories",
  "Fashion and style trends",
  "Photography and camera equipment",
  "Cooking and kitchen appliances",
  "DIY and home improvement projects",
  "Pet care and accessories",
  "Outdoor camping and hiking gear",
  "Art and creative supplies",
  "Collectibles and memorabilia",
  "Sports equipment and merchandise",
  "Health and wellness products",
  "Eco-friendly and reusable products",
  "Smart home devices and automation",
  "Music and audio equipment",
  "Personal development and self-help",
  "Vintage and retro items",
  "Educational toys and learning tools",
  "Sustainable fashion and ethical clothing",
  "DIY crafts and handmade products",
  "Home organization and storage solutions",
  "Watches and accessories",
  "Natural and organic skincare",
  "Cycling and biking equipment",
  "Tech gadgets and innovations",
  "Yoga and meditation accessories",
  "Children's toys and educational games",
  "Food and gourmet products",
  "Musical instruments and accessories",
  "Fashionable footwear",
  "Interior decorating and home staging",
  "Comic books and graphic novels",
  "Virtual reality (VR) devices and experiences",
  "Home entertainment systems",
  "Fishing and outdoor gear",
  "DIY gardening and urban farming",
  "Antique and vintage furniture",
  "DIY beauty and skincare recipes",
  "Sci-fi and fantasy merchandise",
  "Board games and puzzles",
  "Novelty and unique gifts",
  "Luxury fashion and accessories",
  "Healthy cooking and recipe ideas",
];

const citiesInSriLanka = [
  "Colombo",
  "Kandy",
  "Galle",
  "Negombo",
  "Jaffna",
  "Anuradhapura",
  "Trincomalee",
  "Polonnaruwa",
  "Batticaloa",
  "Matara",
  "Badulla",
  "Ratnapura",
  "Kurunegala",
  "Gampaha",
  "Kalutara",
  "Hambantota",
  "Matale",
  "Chilaw",
  "Beruwala",
  "Panadura",
  "Puttalam",
  "Kegalle",
  "Mannar",
  "Nuwareliya",
  "Vavuniya",
  "Avissawella",
  "Wattala",
  "Embilipitiya",
  "Monaragala",
  "Horana",
  "Kuliyapitiya",
  "Chavakachcheri",
  "Kattankudy",
  "Battaramulla",
  "Dambulla",
  "Bandarawela",
  "Weligama",
  "Kilinochchi",
  "Nuwara Eliya",
  "Valvettithurai",
  "Kalmunai",
  "Tangalle",
  "Ampara",
  "Eravur",
  "Mullaitivu",
  "Wattegama",
  "Haputale",
  "Kandana",
  "Peliyagoda",
  "Matale",
  "Ambalangoda",
];

module.exports = {
  ProductCategories: productCategories,
  BuyerInterests: buyerInterests,
  CitiesInSriLanka: citiesInSriLanka,
};
